# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c26ac63ed304705a9208464eec399121105ee29fdb4a42351c6fcfdd69161deaab2919ccb9474cf60e5f7239682438884d84fda7ded14a78383977c19152e9

test:
  secret_key_base: ea4c5318169b9d3511bb60d4c393b3ba9e4d7be9615101b184b73f4dd159ff1f2b007ff5f43c276eddeb841f5fb677278559379c22d94eebaaebeea60d3661bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
